name: WDIO Tests

on:
  workflow_dispatch:
    inputs:
      test_env:
        description: 'Environment'
        default: 'dev'
        type: choice
        options: [dev, staging, prod]
      targets:
        description: 'Comma-separated list of targets to run. e.g. web, api, @smoke, ./tests/web/todo.spec.ts'
        required: true
        type: string

jobs:
  run-tests:
    uses: ./.github/workflows/wdio-template.yml
    with:
      test_env: ${{ inputs.test_env }}
      targets: ${{ inputs.targets }}
    secrets: inherit
